repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: terragrunt-hclfmt
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: goimports
      - id: golint
      - id: yapf
      - id: helmlint
      - id: markdown-link-check
